### ISSUE TITLE
Colorpicker does not position relative to the element under scrollable container

### ISSUE THREAD

**Issue by rfinquiron** [zzzhan/bootstrap-colorpicker-plus#5]
I have a colorpicker element under scrollable container, the colorpicker works well, but if I scroll down the container the picker remains at the same position while the element scrolls down. Can you suggest a fix for this.

Colorpicker is at right position now
<img width="305" alt="screen shot 2016-06-06 at 9 48 45 am" src="https://cloud.githubusercontent.com/assets/4939880/15812970/fabdba6c-2bcb-11e6-968a-abe3b19a6ac5.png">

Now if I scroll up or down, the colorpicker does not position relative to the element.
<img width="311" alt="screen shot 2016-06-06 at 9 46 37 am" src="https://cloud.githubusercontent.com/assets/4939880/15812979/0d492676-2bcc-11e6-8daa-0cf7b7af2da5.png">

**Comment by zzzhan** [comment]
Try to use the dropdown-menu and embed the color picker into it.
You can refer to the sample#4 of the demo page:http://zzzhan.github.io/bootstrap-colorpicker-plus

**Comment by zzzhan** [comment]
@rfinquiron Have you solved your issue? I will close it.

**Comment by rfinquiron** [comment]
It solves the issue, Thanks. But we cant have a textbox in this case for the user to see the color hash value after color selection. Would have been great if the colorpicker in first example itself could be positioned relative to the element. 
It can be done if we can pass the container element where to append the colorpicker instead of directly appending to the body. We can pass the container as the scrollable div which have position;relative style.

**Comment by zzzhan** [comment]
@rfinquiron You can have a texbox with a dropdown button next to it. And set the hash value to the textbox on the listener `changeColor`.
If you want to improve or fix bugs, you can pull requests. Thanks!

**Comment by rfinquiron** [comment]
Thanks
